vqpy/README.md

Add code structure doc.
Add code structure doc.
None
None
None

Add code structure doc

---

README.md

Update installation doc with pip install
Step by step guide of using pip install to install vqpy
None 
Examples

Update installation doc with pip install

---

setup.py

Fix install vqpy on colab
Manually tested (https://colab.research.google.com/drive/1i3cT9JKAYxvDZg2O50nN7E4YRM4uX3mI?usp=sharing)

Fix install vqpy on colab

---

README.md

Update Readme with linux installation

---

.github/workflows/lint.yaml

Lint test checks code in `example/`, and code changes in `example/` don't trigger the test.

All changes will trigger lint check

---

examples/person_search/main.py
examples/person_search/models.py

Fix lint for person search example

---

test/unit_tests/backend/operator/test_frame_filter.py
vqpy/backend/operator/frame_filter.py
vqpy/backend/operator/object_detector.py
vqpy/backend/operator/video_reader.py

Add frame filter operator 
None 
UT
None

Add frame filter operator 

---

vqpy/operator/tracker/byte_tracker.py
vqpy/operator/tracker/multiclass_tracker.py

Remove FrameStream ctx in byte tracker

---

test/unit_tests/backend/operator/test_vobj_filter.py
vqpy/backend/frame.py
vqpy/backend/operator/vobj_filter.py

Add vobj filter

---

test/unit_tests/backend/operator/test_tracker.py
vqpy/backend/frame.py
vqpy/backend/operator/tracker.py
vqpy/operator/tracker/byte_tracker.py
vqpy/operator/tracker/multiclass_tracker.py

Add tracker

---

test/unit_tests/backend/operator/test_object_detector.py
vqpy/backend/operator/object_detector.py

Change detector kwargs

---

.github/workflows/unit_test.yaml
test/unit_tests/backend/plan/run_plan.py
test/unit_tests/backend/plan/run_plan_person.py
test/unit_tests/backend/plan/test_plan.py
test/unit_tests/backend/plan/test_plan_person.py
test/unit_tests/fake_yolox.py
vqpy/backend/frame.py
vqpy/backend/operator/frame_filter.py
vqpy/backend/operator/vobj_filter.py
vqpy/backend/operator/vobj_projector.py
vqpy/backend/plan/__init__.py
vqpy/backend/plan/plan_node.py
vqpy/frontend/query/__init__.py
vqpy/frontend/query/query.py
vqpy/frontend/vobj/__init__.py
vqpy/frontend/vobj/predicates.py
vqpy/frontend/vobj/property.py
vqpy/frontend/vobj/vobj.py

New frontend and Planner

---

vqpy/frontend/vobj/common.py

add uncomputedProperty

---

.github/workflows/unit_test.yaml
test/unit_tests/backend/operator/test_vobj_projector.py
vqpy/backend/operator/vobj_projector.py

Support vobj project with video metadata and vobj image dependencies

---

vqpy/backend/plan/plan_node.py

Remove hardcode fps when creating tracker in planner

---

test/unit_tests/backend/plan/run_plan.py
vqpy/frontend/vobj/predicates.py
vqpy/frontend/vobj/property.py

Support more compare functions in frontend

---

test/unit_tests/backend/plan/run_plan_person.py
vqpy/frontend/vobj/common.py
vqpy/frontend/vobj/predicates.py
vqpy/frontend/vobj/vobj.py

Planner automatically generates projector nodes for dependency properties

---

vqpy/frontend/vobj/vobj.py

Add image and video metadata as vobj builtin property

---

vqpy/backend/operator/vobj_projector.py
vqpy/backend/plan/plan_node.py

Add projector node for properties in `frame_output`

---

test/unit_tests/backend/plan/run_plan.py
test/unit_tests/backend/plan/run_plan_person.py
vqpy/backend/plan/plan_node.py
vqpy/frontend/vobj/vobj.py

Add output formatter operator and return an iterator for real-time query

---

test/unit_tests/backend/operator/test_vobj_projector.py
vqpy/backend/operator/vobj_projector.py

Enable property that depends on itself

---

test/unit_tests/backend/operator/test_vobj_projector.py

Refactor UT

---

vqpy/backend/operator/output_formatter.py

add output formatter

---

examples/list_red_moving_vehicle/README.md
examples/list_red_moving_vehicle/getcolor.py
examples/list_red_moving_vehicle/main.py
examples/list_red_moving_vehicle/old_frontend.py
vqpy/backend/plan/plan_node.py
vqpy/frontend/vobj/vobj.py

Red Moving car example with new frontend

---

Dockerfile
requirements.txt
setup.py

Add dockerfile

---

README.md

Add docker installation documents

---

test/unit_tests/backend/plan/run_plan_person.py
vqpy/backend/frame.py
vqpy/query/vobj_constraint.py

Add self-dependent property in test cases

---

test/unit_tests/backend/operator/test_vobj_projector.py
vqpy/__init__.py
vqpy/backend/operator/vobj_projector.py
vqpy/backend/plan_nodes/vobj_projector.py
vqpy/frontend/vobj/common.py
vqpy/frontend/vobj/property.py

Consider property indirectly depends on historical properties as stateful

---

examples/loitering/new_frontend.py

New loitering example with in-region-time

---

examples/loitering/new_frontend.py

change args in loitering example

---

examples/README.md
examples/loitering/new_frontend.py
vqpy/__init__.py
vqpy/utils/visualize.py

Add Visualization (save output as video)

---

README.md
docs/old_frontend.md

Change Readme example to the new frontend usage

---

README.md

Update README.md with paper badge
